### ISSUE TITLE
Multiple players

### ISSUE THREAD

**Issue by frozenkp** [ancientlore/go-mcpi-api#1]
How can I use go-mcpi-api with multiple players server like the project below?
https://github.com/teachthenet/TeachCraft-Challenges

By the way,If it can work with multiple players server,how can I change the player name in getPos() and setPos() ?

**Comment by ancientlore** [comment]
I have not tried that project. In theory, it should work with any server that supports the [Minecraft Pi Protocol](https://github.com/ancientlore/go-mcpi-api/blob/master/mcpi_protocol_spec.txt). When I created this, the protocol did not have a way to set the player name. It looks like the TeachCraft project is based on the same protocol, but has some extensions provided by RaspberryJuice (like setting the player name). I have not implemented those extensions...

**Comment by frozenkp** [comment]
Thanks for your response.
I forked your project and compared it with the original mcpi. Then,I made my own version based on yours.
https://github.com/FrozenKP/go-mcpi-api

Thanks for your help
